name: ccxgui
version: 0.1.0
summary: Extract subtitles from any media file.
description: CCExtractor is the de-factor open source standard for closed captions / subtitles extraction from any media file. While the software itself belong to the niche category (main users being universities, media companies and enthusiasts) its output (meaning the .srt files it generates) is used by millions. If you've ever downloaded an external subtitle file for a TV show - most likely the original file came from CCExtractor.

confinement: strict
base: core18
grade: stable

slots:
  dbus-ccxgui:
    interface: dbus
    bus: session
    name: org.ccextractor.gui

parts:
  ccextractor: 
    plugin: nil
    source: https://github.com/CCExtractor/ccextractorfluttergui/files/6949923/ccx.zip
    stage-packages: [libglew-dev, libglfw3-dev, cmake, gcc, libcurl4-gnutls-dev, tesseract-ocr, tesseract-ocr-dev, libleptonica-dev]
    
  ccxgui:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

apps:
  ccxgui:
    command: ccxgui
    extensions: [flutter-master]
    plugs:
    - home
    - network
    slots:
      - dbus-ccxgui
