name: Upload artifact

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Install Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'master'
    - name: Enable desktop support
      run: flutter config --enable-windows-desktop
    - name: Build Windows app
      run: flutter build windows
    - name: Copy VC redistributables
      run: |
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
        Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
      working-directory: ./build/windows/runner/Release
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Flutter GUI Windows
        path: |
          ./build/windows/runner/Release/*.exe
          ./build/windows/runner/Release/*.dll
          ./build/windows/runner/Release/data

  build_linux:
      runs-on: ubuntu-latest
      steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'master'
      - name: Enable desktop support
        run: flutter config --enable-linux-desktop
      - name: Build Linux app
        run: | 
          pwd
          flutter build linux
        working-directory: ./build/linux/x64/release/bundle
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: CCExtractor Flutter GUI Linux
          path: ./build/linux/x64/release/bundle/
